import Card from '../public/Card'

let data = {
  royalStraightFlush: [
    new Card('ACE', 'HEARTS'),
    new Card('KING', 'HEARTS'),
    new Card('QUEEN', 'HEARTS'),
    new Card('JACK', 'HEARTS'),
    new Card('10', 'HEARTS'),
  ],
  kHighStraightFlush: [
    new Card('9', 'HEARTS'),
    new Card('KING', 'HEARTS'),
    new Card('QUEEN', 'HEARTS'),
    new Card('JACK', 'HEARTS'),
    new Card('10', 'HEARTS'),
  ],
  fiveHighStraightFlush: [
    new Card('5', 'HEARTS'),
    new Card('4', 'HEARTS'),
    new Card('3', 'HEARTS'),
    new Card('2', 'HEARTS'),
    new Card('ACE', 'HEARTS'),
  ],
  fourOfAKindFace: [
    new Card('JACK', 'SPADES'),
    new Card('JACK', 'HEARTS'),
    new Card('QUEEN', 'CLUBS'),
    new Card('JACK', 'DIAMONDS'),
    new Card('JACK', 'CLUBS'),
  ],
  fourOfAKindNum: [
    new Card('7', 'SPADES'),
    new Card('7', 'HEARTS'),
    new Card('QUEEN', 'CLUBS'),
    new Card('7', 'DIAMONDS'),
    new Card('7', 'CLUBS'),
  ],
  fullHouseFaces: [
    new Card('QUEEN', 'SPADES'),
    new Card('QUEEN', 'HEARTS'),
    new Card('QUEEN', 'CLUBS'),
    new Card('ACE', 'DIAMONDS'),
    new Card('ACE', 'CLUBS'),
  ],
  fullHouseFaceNum: [
    new Card('KING', 'SPADES'),
    new Card('KING', 'HEARTS'),
    new Card('KING', 'CLUBS'),
    new Card('2', 'DIAMONDS'),
    new Card('2', 'CLUBS'),
  ],
  fullHouseNums: [
    new Card('8', 'SPADES'),
    new Card('8', 'HEARTS'),
    new Card('8', 'CLUBS'),
    new Card('3', 'DIAMONDS'),
    new Card('3', 'CLUBS'),
  ],
  flushTwoPair: [
    new Card('2', 'HEARTS'),
    new Card('8', 'HEARTS'),
    new Card('8', 'HEARTS'),
    new Card('3', 'HEARTS'),
    new Card('3', 'HEARTS'),
  ],
  flushOnePair: [
    new Card('2', 'DIAMONDS'),
    new Card('8', 'DIAMONDS'),
    new Card('8', 'DIAMONDS'),
    new Card('1', 'DIAMONDS'),
    new Card('3', 'DIAMONDS'),
  ],
  flush: [
    new Card('2', 'DIAMONDS'),
    new Card('8', 'DIAMONDS'),
    new Card('JACK', 'DIAMONDS'),
    new Card('1', 'DIAMONDS'),
    new Card('3', 'DIAMONDS'),
  ],
  straightAceHigh: [
    new Card('ACE', 'SPADES'),
    new Card('KING', 'DIAMONDS'),
    new Card('QUEEN', 'HEARTS'),
    new Card('JACK', 'HEARTS'),
    new Card('10', 'DIAMONDS'),
  ],
  straightFiveHigh: [
    new Card('ACE', 'SPADES'),
    new Card('2', 'DIAMONDS'),
    new Card('3', 'HEARTS'),
    new Card('4', 'HEARTS'),
    new Card('5', 'DIAMONDS'),
  ],
  straightQueenHigh: [
    new Card('QUEEN', 'SPADES'),
    new Card('10', 'DIAMONDS'),
    new Card('8', 'HEARTS'),
    new Card('9', 'HEARTS'),
    new Card('JACK', 'DIAMONDS'),
  ],
  threeOfAKindFace: [
    new Card('QUEEN', 'SPADES'),
    new Card('QUEEN', 'DIAMONDS'),
    new Card('QUEEN', 'HEARTS'),
    new Card('9', 'HEARTS'),
    new Card('JACK', 'DIAMONDS'),
  ],
  threeOfAKindNum: [
    new Card('7', 'SPADES'),
    new Card('7', 'DIAMONDS'),
    new Card('7', 'HEARTS'),
    new Card('9', 'HEARTS'),
    new Card('JACK', 'DIAMONDS'),
  ],
  twoPairFace: [
    new Card('QUEEN', 'SPADES'),
    new Card('QUEEN', 'DIAMONDS'),
    new Card('JACK', 'HEARTS'),
    new Card('7', 'HEARTS'),
    new Card('JACK', 'DIAMONDS'),
  ],
  twoPairFaceNum: [
    new Card('QUEEN', 'SPADES'),
    new Card('QUEEN', 'DIAMONDS'),
    new Card('JACK', 'HEARTS'),
    new Card('7', 'HEARTS'),
    new Card('7', 'DIAMONDS'),
  ],
  twoPairNums: [
    new Card('2', 'SPADES'),
    new Card('2', 'DIAMONDS'),
    new Card('JACK', 'HEARTS'),
    new Card('7', 'HEARTS'),
    new Card('7', 'DIAMONDS'),
  ],
  onePairFace: [
    new Card('2', 'SPADES'),
    new Card('ACE', 'DIAMONDS'),
    new Card('JACK', 'HEARTS'),
    new Card('JACK', 'HEARTS'),
    new Card('7', 'DIAMONDS'),
  ],
  onePairNum: [
    new Card('2', 'SPADES'),
    new Card('ACE', 'DIAMONDS'),
    new Card('2', 'HEARTS'),
    new Card('JACK', 'HEARTS'),
    new Card('7', 'DIAMONDS'),
  ],
  highCard1: [
    new Card('2', 'SPADES'),
    new Card('ACE', 'DIAMONDS'),
    new Card('3', 'HEARTS'),
    new Card('JACK', 'HEARTS'),
    new Card('7', 'DIAMONDS'),
  ],
  highCard2: [
    new Card('3', 'SPADES'),
    new Card('QUEEN', 'DIAMONDS'),
    new Card('4', 'HEARTS'),
    new Card('JACK', 'HEARTS'),
    new Card('KING', 'DIAMONDS'),
  ],
  highCard3: [
    new Card('7', 'SPADES'),
    new Card('QUEEN', 'DIAMONDS'),
    new Card('ACE', 'HEARTS'),
    new Card('JACK', 'HEARTS'),
    new Card('KING', 'DIAMONDS'),
  ],
  highCard4: [
    new Card('ACE', 'SPADES'),
    new Card('2', 'DIAMONDS'),
    new Card('3', 'HEARTS'),
    new Card('4', 'HEARTS'),
    new Card('KING', 'DIAMONDS'),
  ],
}

export default data;
